model:
  num_classes: 21
  aspp_channels: 256
  decoder_low_channels: 48
  pretrained_backbone: true

data:
  root: "/content/data"
  dataset_name: "pascal_voc"
  years: ["2007", "2012"]
  crop_size: 384
  num_workers: 4
  val_num_workers: 2
  val_split: "val"
  download: false
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2
  coco:
    enabled: true
    img_root: "/content/coco/train2017"
    ann_file: "/content/coco/annotations/instances_train2017.json"
    filter_empty: true
    overlap_policy: "smallest_first"
    mask_cache_dir: "/content/coco/voc_masks"

training:
  batch_size: 24
  val_batch_size: 16
  total_iters: 100000
  log_interval: 100
  eval_interval: 4000
  learning_rate: 1.0e-3
  backbone_lr_scale: 0.25
  weight_decay: 1.0e-4
  warmup_iters: 1000
  freeze_iters: 3000
  resume: false
  amp: true
  grad_clip_norm: 1.0
  dice_weight: 1.0
  lovasz_weight: 0.5
  ema_decay: 0.9999
  ema_update_every: 1

checkpoint:
  dir: "checkpoints"
  # train.py writes only:
  #   best_ema_<run_name>.pth
  #   last_<run_name>.pth

wandb:
  team: "tmdgk115-sungkyunkwan-university"
  project: "osai-project01"
  run_name: "MobileNetV3_Large_ASPP256"

device: "cuda"
seed: 42
