model:
  num_classes: 21

data:
  root: "/content/data"
  dataset_name: "pascal_voc"
  years: ["2007", "2012"]
  crop_size: 384
  num_workers: 2
  val_num_workers: 0
  val_split: "val"
  download: false
  pin_memory: true
  preload: true
  coco:
    enabled: true
    img_root: "/content/coco/train2017"
    ann_file: "/content/coco/annotations/instances_train2017.json"
    filter_empty: true
    overlap_policy: "smallest_first"
    mask_cache_dir: "/content/coco/voc_masks"

training:
  batch_size: 24
  val_batch_size: 16
  total_iters: 100000
  log_interval: 100
  eval_interval: 4000
  learning_rate: 1.0e-3
  backbone_lr_scale: 0.5
  weight_decay: 1.0e-4
  warmup_iters: 500
  freeze_iters: 3000
  resume: false
  amp: true
  dice_weight: 1.0
  lovasz_weight: 0.5
  ema_decay: 0.9998
  ema_update_every: 8

checkpoint:
  dir: "/content/drive/MyDrive/checkpoints"
  # train.py writes only:
  #   best_ema_<run_name>.pth
  #   last_<run_name>.pth

wandb:
  team: "tmdgk115-sungkyunkwan-university"
  project: "osai-project01"
  run_name: "MobileNet_Project01"

device: "cuda"
seed: 42
